# Generated by Django 4.1.5 on 2023-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBio', '0002_pendidikan_pengalaman_alter_bio_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
