# Generated by Django 4.1.5 on 2023-01-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBio', '0003_bio_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='Pendidikan',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='Pengalaman_Kerja',
        ),
        migrations.AddField(
            model_name='pendidikan',
            name='Nama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBio.bio'),
        ),
        migrations.AddField(
            model_name='pengalaman',
            name='Nama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBio.bio'),
        ),
    ]
