# Generated by Django 4.1.5 on 2023-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBio', '0004_remove_bio_pendidikan_remove_bio_pengalaman_kerja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='Foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
