# Generated by Django 4.1.5 on 2023-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBio', '0005_alter_bio_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='Foto',
        ),
    ]
